<?php

/**
 * Plugin definition
 */
$plugin = array(
  'title' => t('Work block'),
  'description' => t('Displays a sample front page block'),
  'single' => TRUE,
  'category' => array(t('Isis One')),
  'render callback' => 'vih_plugins_work_block_content_type_render',
);


/**
 * Render Callback
 */
function vih_plugins_work_block_content_type_render($subtype, $conf, $args, $context) {
  $block = new stdClass();
  $block->content = '<!-- WORK -->
		<section id="work" class="alternate arrow-down">
			<div class="container">
				<header class="text-center">
					<h1>OUR WORK</h1>
				</header>

				<div class="divider"><!-- lines divider --></div>

				<article>
					<p>
						Bacon ipsum dolor sit amet meatball shank pork chop capicola fatback pork loin sirloin flank. Andouille tongue corned beef rump pork loin shank meatball capicola turducken venison shankle kevin pancetta tri-tip boudin. Bacon ipsum dolor sit amet meatball shank pork chop capicola fatback pork loin sirloin flank.
					</p>
				</article>

				<div id="portfolio" class="text-center animate_fade_in">

					<!-- PORTFOLIO FILTER -->
					<div class="text-center">
						<ul class="nav nav-tabs bstrap-tabs isotope-filter" data-sort-id="isotope-list" data-option-key="filter">
							<li data-option-value="*" class="active"><a href="#">ALL</a></li>
							<li data-option-value=".image"><a href="#">IMAGES</a></li>
							<li data-option-value=".brand"><a href="#">BRANDING</a></li>
							<li data-option-value=".video"><a href="#">VIDEO</a></li>
						</ul>
					</div>
					<!-- /PORTFOLIO FILTER -->


					<div class="row">

						<ul class="sort-destination isotope" data-sort-id="isotope-list">

							<li class="isotope-item col-sm-6 col-md-4 image"><!-- item -->
								<a class="popup-image" href="/panopoly/sites/all/themes/isis_one/assets/images/preview/slider/1.jpg">
									<img src="/panopoly/sites/all/themes/isis_one/assets/images/preview/content/portfolio/p1.jpg" class="img-responsive" alt="img" />
									<div class="caption">
										<i class="rounded fa fa-camera"></i>
										<h3>PROJECT TITLE</h3>
										<p>Image Popup</p>
									</div>
								</a>
							</li>

							<li class="isotope-item col-sm-6 col-md-4 video"><!-- item -->
								<a class="popup-video" href="http://www.youtube.com/watch?v=kh29_SERH0Y?rel=0">
									<img src="/panopoly/sites/all/themes/isis_one/assets/images/preview/content/portfolio/p2.jpg" class="img-responsive" alt="img" />
									<div class="caption">
										<i class="rounded fa fa-film"></i>
										<h3>PROJECT TITLE</h3>
										<p>Youtube Video</p>
									</div>
								</a>
							</li>

							<li class="isotope-item col-sm-6 col-md-4 video brand"><!-- item -->
								<a class="popup-video" href="http://vimeo.com/23630702">
									<img src="/panopoly/sites/all/themes/isis_one/assets/images/preview/content/portfolio/p3.jpg" class="img-responsive" alt="img" />
									<div class="caption">
										<i class="rounded fa fa-film"></i>
										<h3>PROJECT TITLE</h3>
										<p>Vimeo Video</p>
									</div>
								</a>
							</li>

							<li class="isotope-item col-sm-6 col-md-4 brand"><!-- item -->
								<a class="external ajax-project" href="project-external-1.html">
									<img src="/panopoly/sites/all/themes/isis_one/assets/images/preview/content/portfolio/p4.jpg" class="img-responsive" alt="img" />
									<div class="caption">
										<i class="rounded fa fa-link"></i>
										<h3>PROJECT TITLE</h3>
										<p>External Project 1</p>
									</div>
								</a>
							</li>

							<li class="isotope-item col-sm-6 col-md-4 brand"><!-- item -->
								<a class="external ajax-project" href="project-external-2.html">
									<img src="/panopoly/sites/all/themes/isis_one/assets/images/preview/content/portfolio/p5.jpg" class="img-responsive" alt="img" />
									<div class="caption">
										<i class="rounded fa fa-link"></i>
										<h3>PROJECT TITLE</h3>
										<p>External Project 2</p>
									</div>
								</a>
							</li>

							<li class="isotope-item col-sm-6 col-md-4 brand"><!-- item -->
								<a class="external ajax-project" href="project-external-3.html">
									<img src="/panopoly/sites/all/themes/isis_one/assets/images/preview/content/portfolio/p6.jpg" class="img-responsive" alt="img" />
									<div class="caption">
										<i class="rounded fa fa-link"></i>
										<h3>PROJECT TITLE</h3>
										<p>External Project 3</p>
									</div>
								</a>
							</li>

						</ul>
					</div>

				</div>

			
			</div>
		</section>
		<!-- /WORK -->
';

  return $block;
}
