<?php

/**
 * @file
 * Provides multiple plugins for the VIH
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function vih_plugins_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_theme().
 */
function vih_plugins_theme() {
  return array(
    'social_widget' => array(
      'variables' => array('networks' => NULL),
      'template' => 'templates/social-widget',
      'file' => 'vih_plugins.theme.inc',
    ),
  );
}
