<?php

/**
 * @file
 * Provides multiple plugins for the VIH
 */

/**
 * Implements hook_ctools_plugin_directory().
 */ 
function vih_plugins_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_theme().
 */
function vih_plugins_theme() {
  return array(
    'contact_info_pane' => array(
      'variables' => array('address' => NULL, 'phone' => NULL),
      'template' => 'templates/contact-info-pane',
      'file' => 'vih_plugins.theme.inc',
    ),
    'logo_site_name_pane' => array(
      'variables' => array(),
      'template' => 'templates/logo-site-name-pane',
      'file' => 'vih_plugins.theme.inc',
    ),
    'navigation' => array(
      'variables' => array(),
      'template' => 'templates/navigation',
      'file' => 'vih_plugins.theme.inc',
    ),
  );
}
